version: "3.8"

services:
  web:
    build: ./test_task
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      ./test_task/test_task/.env
    ports:
      - 8000:8000

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xone

  redis:
    image: redis
    restart: always

  celery_beat:
    build: ./test_task
    command: celery -A test_task beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

volumes:
  postgres_data:
